# Generated by Django 5.0.3 on 2024-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('room', models.IntegerField()),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
