# Generated by Django 5.0.3 on 2024-04-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0002_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
