# Generated by Django 5.0.3 on 2024-04-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0004_alter_hotels_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('order_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
