# Generated by Django 5.0.3 on 2024-04-12 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0008_alter_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='check_in_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hotels',
            name='check_out_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
