# Generated by Django 5.0.3 on 2024-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0009_hotels_check_in_date_hotels_check_out_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=10)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=111)),
                ('password1', models.IntegerField()),
                ('password2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='pessanger_detail',
        ),
    ]
