# Generated by Django 5.0.3 on 2024-04-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0011_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('package', 'Package')], default='hotel', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
