# Generated by Django 5.0.3 on 2024-04-18 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0012_booking_booking_type_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('num_passengers', models.IntegerField()),
                ('flight_class', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('from_city', models.CharField(max_length=30)),
                ('to_city', models.CharField(max_length=30)),
                ('depart', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
