# Generated by Django 5.0.3 on 2024-04-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0013_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='num_passengers',
        ),
    ]
