# Generated by Django 5.0.3 on 2024-04-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellit', '0014_remove_flight_num_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_class',
        ),
    ]
